name: my_finance
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  bloc: ^9.0.0
  cloud_firestore: ^6.0.0
  equatable: ^2.0.7
  firebase_auth: ^6.0.1
  firebase_core: ^4.0.0
  fl_chart: ^1.1.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_dotenv: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
